/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f41f87e1-334f-425e-8f87-af124fd93167",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ApHCmpIhV",
    "aws_user_pools_web_client_id": "jlj3ta594q3c322i1hqmqngov",
    "oauth": {
        "domain": "signin-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3001/",
        "redirectSignOut": "http://localhost:3001/home/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
